# Generated by Django 5.2.7 on 2025-11-11 14:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "writing_q1_prompt",
                    models.TextField(
                        default="Explain as if writing for an educated but non-expert audience the nature of your postgraduate research if applying for a PhD or the reasons for your choice of taught postgraduate or (undergraduate) programme.",
                        editable=False,
                    ),
                ),
                ("writing_answer_draft", models.TextField(blank=True)),
                ("writing_answer_final", models.TextField(blank=True)),
                ("writing_submitted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
