# Generated by Django 5.2.7 on 2025-11-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="llm_question_1",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="assessment",
            name="llm_question_2",
            field=models.TextField(blank=True),
        ),
    ]
