# Generated by Django 5.2.7 on 2025-11-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0002_assessment_llm_question_1_assessment_llm_question_2"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="llm_question_1_answer_draft",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="assessment",
            name="llm_question_1_answer_final",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="assessment",
            name="llm_question_1_answer_submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
