# Generated by Django 5.2.7 on 2025-11-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0003_assessment_llm_question_1_answer_draft_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="llm_question_2_answer_draft",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="assessment",
            name="llm_question_2_answer_final",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="assessment",
            name="llm_question_2_answer_submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
