# Generated by Django 5.2.7 on 2025-11-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0004_assessment_llm_question_2_answer_draft_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="listening_answer_draft",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="assessment",
            name="listening_answer_final",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="assessment",
            name="listening_answer_submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assessment",
            name="listening_q1_prompt",
            field=models.TextField(
                default="You are going to listen to a lecture related to your subject area. The lecture is approximately five minutes long. Write a short summary of the lecture.",
                editable=False,
            ),
        ),
    ]
