# Generated by Django 5.2.7 on 2025-11-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0005_assessment_listening_answer_draft_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessment",
            name="listening_q1_prompt",
            field=models.TextField(
                default="You are going to listen to a lecture related to your subject area. The lecture is approximately ten minutes long. Write a short summary of the lecture.",
                editable=False,
            ),
        ),
    ]
