# Generated by Django 5.2.7 on 2025-11-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0006_alter_assessment_listening_q1_prompt"),
    ]

    operations = [
        migrations.CreateModel(
            name="DebateTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "topic_number",
                    models.PositiveSmallIntegerField(
                        help_text="Short numeric identifier, e.g. 1–10.", unique=True
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Short label, e.g. 'ubi', 'ai-decisions'.", unique=True
                    ),
                ),
                ("question", models.TextField(help_text="Full debate question shown to students.")),
                (
                    "position_a_title",
                    models.CharField(help_text="Short heading for Position A.", max_length=255),
                ),
                ("position_a_body", models.TextField(help_text="Full text for Position A.")),
                (
                    "position_b_title",
                    models.CharField(help_text="Short heading for Position B.", max_length=255),
                ),
                ("position_b_body", models.TextField(help_text="Full text for Position B.")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Only active topics are used for new assessments."
                    ),
                ),
            ],
            options={
                "verbose_name": "Debate topic",
                "verbose_name_plural": "Debate topics",
                "ordering": ("topic_number",),
            },
        ),
    ]
