# Generated by Django 5.2.7 on 2025-11-27 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0007_debatetopic"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="reading_answer_draft",
            field=models.TextField(
                blank=True, help_text="Student's draft answer for the reading comprehension task."
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="reading_answer_final",
            field=models.TextField(
                blank=True, help_text="Student's final answer for the reading comprehension task."
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="reading_answer_submitted_at",
            field=models.DateTimeField(
                blank=True, help_text="When the reading final answer was submitted.", null=True
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="reading_debate",
            field=models.ForeignKey(
                blank=True,
                help_text="Debate topic shown to the student for the Reading Comprehension step.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assessments",
                to="assessments.debatetopic",
            ),
        ),
    ]
