# Generated by Django 5.2.7 on 2025-12-08 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0008_assessment_reading_answer_draft_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssessmentEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "student_email",
                    models.EmailField(
                        help_text="Student email at the time of evaluation.", max_length=254
                    ),
                ),
                (
                    "student_usn",
                    models.CharField(
                        help_text="Student USN at the time of evaluation.", max_length=64
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        help_text="When the assessment was fully submitted (reading final)."
                    ),
                ),
                (
                    "completion_duration",
                    models.DurationField(
                        help_text="Wall-clock time from writing submission to final reading submission."
                    ),
                ),
                (
                    "llm_evaluation_text",
                    models.TextField(
                        blank=True, help_text="Short analytic evaluation generated by the LLM."
                    ),
                ),
                (
                    "llm_model_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the LLM model used for this evaluation.",
                        max_length=100,
                    ),
                ),
                (
                    "llm_generated_at",
                    models.DateTimeField(
                        blank=True, help_text="When the LLM evaluation was generated.", null=True
                    ),
                ),
                (
                    "llm_error",
                    models.TextField(
                        blank=True, help_text="Error message if the LLM evaluation failed."
                    ),
                ),
                (
                    "recommendation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MET_CONDITION", "Meets condition – no language course required"),
                            (
                                "RECOMMENDED_IN_SESSIONAL",
                                "Meets condition – in-sessional support recommended",
                            ),
                            ("REQUIRED_IN_SESSIONAL", "In-sessional support required"),
                            ("RECOMMENDED_PRE_SESSIONAL", "Pre-sessional course recommended"),
                            ("REQUIRED_PRE_SESSIONAL", "Pre-sessional course required"),
                            ("REFUSED", "Not recommended / refused"),
                        ],
                        help_text="Assessor's final recommendation.",
                        max_length=40,
                    ),
                ),
                (
                    "assessor_comment",
                    models.TextField(
                        blank=True,
                        help_text="Optional assessor comments on the evaluation / assessment.",
                    ),
                ),
                (
                    "exam_marked",
                    models.BooleanField(
                        default=False, help_text="Has this assessment been fully marked?"
                    ),
                ),
                (
                    "phone_follow_up",
                    models.BooleanField(
                        default=False, help_text="Does this case require a phone follow-up?"
                    ),
                ),
                (
                    "exam_archived",
                    models.BooleanField(
                        default=False, help_text="Has this evaluation been archived?"
                    ),
                ),
                (
                    "assessor_reviewed_at",
                    models.DateTimeField(
                        blank=True, help_text="When the assessor last saved changes.", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assessment",
                    models.OneToOneField(
                        help_text="LLM + assessor evaluation for this assessment.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluation",
                        to="assessments.assessment",
                    ),
                ),
                (
                    "assessor",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated the recommendation/comment.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assessments_marked",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
