# Generated by Django 5.2.7 on 2025-12-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0009_assessmentevaluation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessmentevaluation",
            name="recommendation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MET_CONDITION", "Meets condition – no language course required"),
                    (
                        "RECOMMENDED_IN_SESSIONAL",
                        "Meets condition – in-sessional support recommended",
                    ),
                    (
                        "REQUIRED_IN_SESSIONAL_SPEAKING",
                        "In-sessional support required (speaking focus)",
                    ),
                    ("REQUIRED_IN_SESSIONAL", "In-sessional support required"),
                    ("RECOMMENDED_PRE_SESSIONAL", "Pre-sessional course recommended"),
                    ("REQUIRED_PRE_SESSIONAL", "Pre-sessional course required"),
                    ("REFUSED", "Not recommended / refused"),
                ],
                help_text="Assessor's final recommendation.",
                max_length=40,
            ),
        ),
    ]
