# Generated by Django 5.2.7 on 2026-02-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0010_alter_assessmentevaluation_recommendation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessment",
            name="writing_q1_prompt",
            field=models.TextField(
                default="Explain as if writing for an educated but non-expert audience the nature of your postgraduate research if applying for a PhD or the reasons for your choice of taught postgraduate programme.",
                editable=False,
            ),
        ),
    ]
