# Generated by Django 5.2.7 on 2026-10-05

from django.db import migrations, models

OLD_PROMPT = (
    "Explain as if writing for an educated but non-expert audience the nature of your "
    "postgraduate research if applying for a PhD or the reasons for your choice of "
    "taught postgraduate programme."
)
NEW_PROMPT = (
    "Explain the nature of your proposed postgraduate research or the reasons for your "
    "choice of taught postgraduate programme. Write for an educated but non-expert "
    "audience."
)


def _replace_unsubmitted_prompt(apps, old, new):
    # Only students who have not submitted writing get the new wording; submitted
    # answers keep the question they were written for.
    Assessment = apps.get_model("assessments", "Assessment")
    Assessment.objects.filter(writing_submitted_at__isnull=True, writing_q1_prompt=old).update(
        writing_q1_prompt=new
    )


def forwards(apps, schema_editor):
    _replace_unsubmitted_prompt(apps, OLD_PROMPT, NEW_PROMPT)


def backwards(apps, schema_editor):
    _replace_unsubmitted_prompt(apps, NEW_PROMPT, OLD_PROMPT)


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0011_alter_assessment_writing_q1_prompt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessment",
            name="writing_q1_prompt",
            field=models.TextField(default=NEW_PROMPT, editable=False),
        ),
        migrations.RunPython(forwards, backwards),
    ]
