# Generated by Django 5.2.7 on 2026-10-05

from django.db import migrations

# Original 0001 default; 0011 changed the default but left existing rows untouched.
LEGACY_PROMPT = (
    "Explain as if writing for an educated but non-expert audience the nature of your "
    "postgraduate research if applying for a PhD or the reasons for your choice of "
    "taught postgraduate or (undergraduate) programme."
)
NEW_PROMPT = (
    "Explain the nature of your proposed postgraduate research or the reasons for your "
    "choice of taught postgraduate programme. Write for an educated but non-expert "
    "audience."
)


def forwards(apps, schema_editor):
    # Same rule as 0012: only assessments whose writing has not been submitted.
    Assessment = apps.get_model("assessments", "Assessment")
    Assessment.objects.filter(
        writing_submitted_at__isnull=True, writing_q1_prompt=LEGACY_PROMPT
    ).update(writing_q1_prompt=NEW_PROMPT)


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0012_update_writing_q1_prompt"),
    ]

    # Not reversible to the legacy text: after 0012 the two old wordings can't be told apart.
    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
