# Generated by Django 5.2.7 on 2025-11-03 10:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Profile",
                "verbose_name_plural": "Profiles",
            },
        ),
        migrations.AddField(
            model_name="profile",
            name="phone",
            field=models.CharField(
                default="+441234567890",
                help_text="Student contact number (required).",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid phone number (digits, spaces, +, -).",
                        regex="^\\+?[0-9\\s\\-]{7,20}$",
                    )
                ],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                help_text="Linked user account for this profile.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
