# Generated by Django 5.2.7 on 2025-11-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_alter_profile_options_profile_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="subject_area",
            field=models.CharField(
                choices=[
                    ("arts_humanities", "Art and Humanities"),
                    ("computing", "Computing"),
                    ("education", "Education"),
                    ("engineering", "Engineering"),
                    ("environment", "Environment"),
                    ("medicine", "Medicine"),
                    ("physical_sciences", "Physical Sciences"),
                    ("social_sciences", "Social Sciences"),
                    ("generic", "Generic"),
                ],
                default="generic",
                help_text="Student's main subject area (required).",
                max_length=32,
            ),
        ),
    ]
