# Generated by Django 5.2.7 on 2025-11-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_profile_subject_area"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="requires_uk_student_visa",
            field=models.BooleanField(
                help_text="Whether the student requires a visa to study in the UK.", null=True
            ),
        ),
    ]
