# Generated by Django 5.2.7 on 2025-11-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_profile_requires_uk_student_visa"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="has_recent_english_exam",
            field=models.BooleanField(
                help_text="Has the student taken an English language exam in the last five years?",
                null=True,
            ),
        ),
    ]
