# Generated by Django 5.2.7 on 2025-11-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0005_profile_has_recent_english_exam"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="has_recent_english_exam",
            field=models.BooleanField(
                default=False,
                help_text="Has the student taken an English language exam in the last five years?",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="subject_area",
            field=models.CharField(
                choices=[
                    ("arts_humanities", "Art and Humanities"),
                    ("computing", "Computing"),
                    ("education", "Education"),
                    ("engineering", "Engineering"),
                    ("environment", "Environment"),
                    ("medicine", "Medicine"),
                    ("physical_sciences", "Physical Sciences"),
                    ("social_sciences", "Social Sciences"),
                    ("other", "Other"),
                ],
                default="other",
                help_text="Student's main subject area (required).",
                max_length=32,
            ),
        ),
    ]
