# Generated by Django 5.2.7 on 2025-11-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0006_alter_profile_has_recent_english_exam_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="subject_area",
            field=models.CharField(
                choices=[
                    ("arts_humanities", "Art and Humanities"),
                    ("computing", "Computing"),
                    ("education", "Education"),
                    ("engineering", "Engineering"),
                    ("environment", "Environment"),
                    ("medicine", "Medicine"),
                    ("physical_sciences", "Physical Sciences"),
                    ("social_sciences", "Social Sciences"),
                    ("other", "Other"),
                ],
                default="other",
                help_text="Student's main subject area (required).",
                max_length=50,
            ),
        ),
    ]
