# Generated by Django 5.2.7 on 2025-11-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0007_alter_profile_subject_area"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="has_recent_english_exam",
            field=models.BooleanField(
                default=False,
                help_text="Has the student taken an English language exam in the last five years?",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="requires_uk_student_visa",
            field=models.BooleanField(
                default=True, help_text="Whether the student requires a visa to study in the UK."
            ),
        ),
    ]
