# Generated by Django 5.2.7 on 2025-11-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0008_alter_profile_has_recent_english_exam_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="exam_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Select exam..."),
                    ("ielts", "IELTS"),
                    ("toefl", "TOEFL"),
                    ("c1", "Cambridge C1 Advanced"),
                    ("c2", "Cambridge C2 Proficiency"),
                ],
                help_text="The type of English language exam taken.",
                max_length=20,
            ),
        ),
    ]
