# Generated by Django 5.2.8 on 2025-11-05 23:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0009_profile_exam_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="exam_date",
            field=models.DateField(
                blank=True,
                help_text="Date of the most recent English exam (required if an exam was taken).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="subject_area",
            field=models.CharField(
                choices=[
                    ("arts_humanities", "Arts and Humanities"),
                    ("computing", "Computing"),
                    ("education", "Education"),
                    ("engineering", "Engineering"),
                    ("environment", "Environment"),
                    ("medicine", "Medicine"),
                    ("physical_sciences", "Physical Sciences"),
                    ("social_sciences", "Social Sciences"),
                    ("other", "Other"),
                ],
                default="other",
                help_text="Student's main subject area (required).",
                max_length=50,
            ),
        ),
        migrations.AddConstraint(
            model_name="profile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("has_recent_english_exam", False),
                    models.Q(
                        models.Q(("exam_type", ""), _negated=True), ("exam_date__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="exam_requires_type_and_date",
            ),
        ),
    ]
