# Generated by Django 5.2.7 on 2025-11-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0010_profile_exam_date_alter_profile_subject_area_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="listening_score",
            field=models.DecimalField(
                blank=True, decimal_places=1, help_text="Listening score.", max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="overall_manual_override",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="overall_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Overall score (auto-calculated by default).",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="reading_score",
            field=models.DecimalField(
                blank=True, decimal_places=1, help_text="Reading score.", max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="speaking_score",
            field=models.DecimalField(
                blank=True, decimal_places=1, help_text="Speaking score.", max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="writing_score",
            field=models.DecimalField(
                blank=True, decimal_places=1, help_text="Writing score.", max_digits=5, null=True
            ),
        ),
    ]
