# Generated by Django 5.2.7 on 2025-11-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0011_profile_listening_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="cambridge_grade",
            field=models.CharField(
                blank=True,
                choices=[("-", "-"), ("a", "A"), ("b", "B"), ("c", "C")],
                help_text="Grade for Cambridge exams (A/B/C). Only for C1/C2.",
                max_length=1,
            ),
        ),
    ]
