# Generated by Django 5.2.8 on 2025-11-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0012_profile_cambridge_grade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="cambridge_grade",
            field=models.CharField(
                blank=True,
                choices=[("a", "A"), ("b", "B"), ("c", "C")],
                help_text="Grade for Cambridge exams (A/B/C). Only for C1/C2.",
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="listening_score",
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="overall_score",
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="reading_score",
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="speaking_score",
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="writing_score",
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
    ]
