# Generated by Django 5.2.8 on 2025-11-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0013_alter_profile_cambridge_grade_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="cambridge_use_of_english",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Cambridge Use of English score (only for C1/C2).",
                max_digits=5,
                null=True,
            ),
        ),
    ]
