# Generated by Django 5.2.8 on 2025-11-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0014_profile_cambridge_use_of_english"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="academic_integrity_confirmed",
            field=models.BooleanField(
                default=False,
                help_text="Student has confirmed the work will be their own unaided effort, completed without the use of AI or large language models (LLMs).",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="academic_integrity_confirmed_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="Timestamp when the student confirmed the honour code.",
                null=True,
            ),
        ),
    ]
