# Generated by Django 5.2.7 on 2025-11-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0017_clear_other_subjects"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="subject_area",
            field=models.CharField(
                choices=[
                    ("arts_humanities", "Arts and Humanities"),
                    ("business_management", "Business and Management"),
                    ("computing", "Computing"),
                    ("education", "Education"),
                    ("engineering", "Engineering"),
                    ("environment", "Environment"),
                    ("medicine", "Medicine"),
                    ("physical_sciences", "Physical Sciences"),
                    ("social_sciences", "Social Sciences"),
                    ("other", "Other"),
                ],
                default="",
                help_text="Student's main subject area (required).",
                max_length=50,
            ),
        ),
    ]
