# Generated by Django 5.2.7 on 2025-11-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0019_migrate_toefl_to_toefl120"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="exam_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Select exam…"),
                    ("ielts", "IELTS (0–9)"),
                    ("toefl_120", "TOEFL (0–120)"),
                    ("toefl_6", "TOEFL (0–6 )"),
                    ("c1", "Cambridge C1 Advanced"),
                    ("c2", "Cambridge C2 Proficiency"),
                ],
                help_text="The type of English language exam taken.",
                max_length=20,
            ),
        ),
    ]
