# Generated by Django 5.2.7 on 2025-11-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0020_alter_profile_exam_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="exam_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Select your exam…"),
                    ("ielts", "IELTS (0–9, half bands)"),
                    ("toefl_120", "TOEFL (0–120)"),
                    ("toefl_6", "TOEFL (0–6, half points)"),
                    ("c1", "Cambridge C1 Advanced (160–210)"),
                    ("c2", "Cambridge C2 Proficiency (180–230)"),
                ],
                help_text="The type of English language exam taken.",
                max_length=20,
            ),
        ),
    ]
