# Generated by Django 5.2.7 on 2025-11-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0022_alter_profile_exam_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="student_number",
            field=models.CharField(
                blank=True,
                help_text="Unique Student Number (USN).",
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
    ]
