# Generated by Django 5.2.7 on 2025-11-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0025_alter_profile_student_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="student_number",
            field=models.CharField(
                help_text="Unique Student Number (USN)", max_length=20, unique=True
            ),
        ),
    ]
