# Generated by Django 5.2.7 on 2025-11-21 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0026_alter_profile_student_number"),
    ]

    operations = []
