# Generated by Django 5.2.7 on 2025-11-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0027_add_student_number_required"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="student_number",
            field=models.CharField(
                blank=True,
                help_text="Unique Student Number (USN)",
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
    ]
