# Generated by Django 5.2.7 on 2026-02-03 09:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0028_alter_profile_student_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="student_number",
            field=models.CharField(
                blank=True,
                help_text="Unique Student Number (USN)",
                max_length=20,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Student number must contain only letters, digits, or hyphens (no spaces or other symbols).",
                        regex="^[A-Za-z0-9-]+$",
                    )
                ],
            ),
        ),
    ]
